import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import User from '../lib/firebase/models/user';

interface UserState {
    id?: string,
    user?: User
}

const initialState: UserState = {};

const setCurrentUserReducer = (state: UserState, action: PayloadAction<UserState>) => {
    //return action.payload;
    state.id = action.payload.id;
    state.user = action.payload.user;
};

export const userSlice = createSlice({
    name: "user",
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    // Use the PayloadAction type to declare the contents of `action.payload`
    reducers: {
        setCurrentUser: setCurrentUserReducer,
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    // extraReducers: (builder) => {}
});

// reducers/actions go in here in order to import them into components
export const { setCurrentUser } = userSlice.actions;

export default userSlice.reducer;
